navbar:
  blog_title: cqh's blog
  ground_glass:
    enable: true
index:
  banner_img: /images/uploads/5.jpg
  banner_img_height: 100
  slogan:
    text: All we have is now.
post:
  banner_img: /images/uploads/7.jpg
  banner_img_height: 70
  default_index_img: ""
archive:
  banner_img: /images/uploads/1.jpg
  banner_img_height: 80
category:
  banner_img: /images/uploads/8.jpg
  banner_img_height: 80
tag:
  banner_img: /images/uploads/4.jpg
  banner_img_height: 80
about:
  banner_img: /images/uploads/6.jpg
  banner_img_height: 80
  avatar: /images/uploads/touxiang.jpg
  name: cqh's blog
  intro: 废物一个
links:
  banner_img: /images/uploads/3.jpg
  banner_img_height: 80
  items:
    - title: Ytterbiumer
      intro: 不怕人矮，就怕志短。小小身高，大大智慧！
      link: https://ybwa.github.io/
      avatar: https://q2.qlogo.cn/g?b=qq&nk=3391935359&s=100
    - title: CHK's blog
      intro: 白昼之光，岂知夜色之深。
      link: https://www.konn.top/
      avatar: https://q1.qlogo.cn/g?b=qq&nk=2603271254&s=640
