navbar:
  blog_title: cqh's blog
  ground_glass:
    enable: true
index:
  banner_img: /images/uploads/5.jpg
  banner_img_height: 100
  slogan:
    text: Life is short. Play more.
post:
  banner_img: /images/uploads/7.jpg
  banner_img_height: 70
  default_index_img: " "
archive:
  banner_img: /images/uploads/1.jpg
  banner_img_height: 80
category:
  banner_img: /images/uploads/8.jpg
  banner_img_height: 80
tag:
  banner_img: /images/uploads/4.jpg
  banner_img_height: 80
about:
  banner_img: /images/uploads/6.jpg
  banner_img_height: 80
  avatar: /images/uploads/touxiang.jpg
  name: cqh's blog
  intro: 废物一个
links:
  banner_img: /images/uploads/3.jpg
  banner_img_height: 80
  items:
    - title: Fluid Repo
      intro: 主题 GitHub 仓库
      link: https://github.com/fluid-dev/hexo-theme-fluid
      avatar: /img/favicon.png
    - title: 暮雨千泷
      intro: 青天白日梦神仙
      link: https://www.myql.xyz
      avatar: https://cdn.jsdelivr.net/gh/leicancun/JSCDN@master/images/circle-cropped.webp
