navbar:
  blog_title: cqh's blog
  ground_glass:
    enable: true
index:
  banner_img: /images/uploads/5.jpg
  banner_img_height: 100
  slogan:
    text: Life is short. Play more.
post:
  banner_img: /images/uploads/7.jpg
  banner_img_height: 70
  default_index_img: https://img.xjh.me/random_img.php?type=bg&ctype=nature&return=302
archive:
  banner_img: /images/uploads/1.jpg
  banner_img_height: 80
category:
  banner_img: /images/uploads/8.jpg
  banner_img_height: 80
tag:
  banner_img: /images/uploads/4.jpg
  banner_img_height: 80
about:
  banner_img: /images/uploads/6.jpg
  banner_img_height: 80
  avatar: /images/uploads/touxiang.jpg
  name: cqh's blog
  intro: 废物一个
links:
  banner_img: /images/uploads/3.jpg
  banner_img_height: 80
  items:
    - title: 白衣博客
      intro: 楼空人不归，云白去时衣。
      link: https://baiyinet.cn
      avatar: https://q2.qlogo.cn/headimg_dl?dst_uin=37502105&spec=640
    - title: 见字如晤
      intro: 从前车马很慢，书信很远，一生只够爱一个人
      link: https://www.jianziruw.com
      avatar: https://www.jianziruw.com/usr/uploads/logo.jpg
    - title: LCZBlog
      intro: 欲買桂花同載酒，終不似，少年遊。
      link: https://licaoz.com
      avatar: https://cdn.jsdelivr.net/gh/licaoz/static/pubicon.png
    - title: Legendgod's Blog
      link: https://legendgod.ml/
      intro: 终幕
      avatar: https://q2.qlogo.cn/g?b=qq&nk=3456261198&s=100
    - title: Macesuted's Blog
      link: https://macesuted.moe/
      intro: Macesuted 可爱！
      avatar: https://q2.qlogo.cn/g?b=qq&nk=1912192337&s=100
    - title: Wer Blog
      link: https://oyyy.cc
      avatar: https://s2.loli.net/2021/12/31/msfnS8iwkglDNAu.jpg
      intro: 是Yy鸭~
    - title: 小孙在摸鱼
      link: https://blog.ivisun.cn/
      intro: 记录小孙的摸鱼经历
      avatar: https://z3.ax1x.com/2021/08/24/hFbKtf.jpg
    - title: 小阳博客
      link: https://www.page2.cn/
      intro: 热爱科技，热爱生活
      avatar: https://q1.qlogo.cn/g?b=qq&nk=3197005320&s=160
    - title: Ytterbiumer
      intro: 不怕人矮，就怕志短。小小身高，大大智慧！
      link: https://ybwa.github.io/
      avatar: https://q2.qlogo.cn/g?b=qq&nk=3391935359&s=100
